### ISSUE TITLE
Problems when I install this package 

### ISSUE THREAD

**Issue by Meng-Ziwei** [Naereen/Jupyter-NBConvert-OCaml#2]
It is fine for me to use jupyter ocaml. However, when I install jupyter_nbccovert_ocaml, I got **_500 : Internal Server Error_** and I can not fix it. What should I do?

**Comment by Naereen** [comment]
Hi,
Have you tried to uninstall jupyter_nbccovert_ocaml?
What do you mean you got a 500 error, where? when? in which context?
Please give more details!

**Comment by Meng-Ziwei** [comment]
Thanks for your reply. I have tried to uninstall both jupyter_nbccovert_ocaml and jupyter but it not works. After several hours of fixing, I uninstalled the whole anaconda and reinstalled it and finally, it worked. In order to find the reason of 500:internal server error, I tried again to install jupyter_nbccovert_ocaml, and I got the same result.
 Here is the output on my terminal. 

`sudo pip install git+https://github.com/Naereen/Jupyter-NBConvert-OCaml

[E 13:11:00.697 NotebookApp] Uncaught exception GET /notebooks/Documents/Ocaml/%E6%9C%AA%E5%91%BD%E5%90%8D1.ipynb (::1)
    HTTPServerRequest(protocol='http', host='localhost:8888', method='GET', uri='/notebooks/Documents/Ocaml/%E6%9C%AA%E5%91%BD%E5%90%8D1.ipynb', version='HTTP/1.1', remote_ip='::1')
    Traceback (most recent call last):
      File "/Users/mengziweidemac/opt/anaconda3/lib/python3.8/site-packages/traitlets/traitlets.py", line 535, in get
        value = obj._trait_values[self.name]
    KeyError: 'template_paths'
    
    During handling of the above exception, another exception occurred:
    
    Traceback (most recent call last):
      File "/Users/mengziweidemac/opt/anaconda3/lib/python3.8/site-packages/tornado/web.py", line 1703, in _execute
        result = await result
      File "/Users/mengziweidemac/opt/anaconda3/lib/python3.8/site-packages/tornado/gen.py", line 748, in run
        yielded = self.gen.send(value)
      File "/Users/mengziweidemac/opt/anaconda3/lib/python3.8/site-packages/notebook/notebook/handlers.py", line 95, in get
        self.write(self.render_template('notebook.html',
      File "/Users/mengziweidemac/opt/anaconda3/lib/python3.8/site-packages/notebook/base/handlers.py", line 512, in render_template
        return template.render(**ns)
      File "/Users/mengziweidemac/opt/anaconda3/lib/python3.8/site-packages/jinja2/environment.py", line 1090, in render
        self.environment.handle_exception()
      File "/Users/mengziweidemac/opt/anaconda3/lib/python3.8/site-packages/jinja2/environment.py", line 832, in handle_exception
        reraise(*rewrite_traceback_stack(source=source))
      File "/Users/mengziweidemac/opt/anaconda3/lib/python3.8/site-packages/jinja2/_compat.py", line 28, in reraise
        raise value.with_traceback(tb)
      File "/Users/mengziweidemac/opt/anaconda3/lib/python3.8/site-packages/notebook/templates/notebook.html", line 1, in top-level template code
        {% extends "page.html" %}
      File "/Users/mengziweidemac/opt/anaconda3/lib/python3.8/site-packages/notebook/templates/page.html", line 154, in top-level template code
        {% block header %}
      File "/Users/mengziweidemac/opt/anaconda3/lib/python3.8/site-packages/notebook/templates/notebook.html", line 115, in block "header"
        {% for exporter in get_frontend_exporters() %}
      File "/Users/mengziweidemac/opt/anaconda3/lib/python3.8/site-packages/notebook/notebook/handlers.py", line 40, in get_frontend_exporters
        for name in get_export_names():
      File "/Users/mengziweidemac/opt/anaconda3/lib/python3.8/site-packages/nbconvert/exporters/base.py", line 141, in get_export_names
        e = get_exporter(exporter_name)(config=config)
      File "/Users/mengziweidemac/opt/anaconda3/lib/python3.8/site-packages/nbconvert/exporters/base.py", line 102, in get_exporter
        if getattr(exporter(config=config), 'enabled', True):
      File "/Users/mengziweidemac/opt/anaconda3/lib/python3.8/site-packages/nbconvert/exporters/templateexporter.py", line 325, in __init__
        super().__init__(config=config, **kw)
      File "/Users/mengziweidemac/opt/anaconda3/lib/python3.8/site-packages/nbconvert/exporters/exporter.py", line 114, in __init__
        self._init_preprocessors()
      File "/Users/mengziweidemac/opt/anaconda3/lib/python3.8/site-packages/nbconvert/exporters/templateexporter.py", line 491, in _init_preprocessors
        conf = self._get_conf()
      File "/Users/mengziweidemac/opt/anaconda3/lib/python3.8/site-packages/nbconvert/exporters/templateexporter.py", line 507, in _get_conf
        for path in map(Path, self.template_paths):
      File "/Users/mengziweidemac/opt/anaconda3/lib/python3.8/site-packages/jupyter_nbconvert_ocaml/__init__.py", line 99, in template_paths
        return super().template_paths + [os.path.join(os.path.dirname(__file__), "templates")]
      File "/Users/mengziweidemac/opt/anaconda3/lib/python3.8/site-packages/traitlets/traitlets.py", line 575, in __get__
        return self.get(obj, cls)
      File "/Users/mengziweidemac/opt/anaconda3/lib/python3.8/site-packages/traitlets/traitlets.py", line 538, in get
        default = obj.trait_defaults(self.name)
      File "/Users/mengziweidemac/opt/anaconda3/lib/python3.8/site-packages/traitlets/traitlets.py", line 1574, in trait_defaults
        raise TraitError("'%s' is not a trait of '%s' "
    traitlets.traitlets.TraitError: 'template_paths' is not a trait of 'OCamlExporter' instances
[E 13:11:00.714 NotebookApp] {
      "Host": "localhost:8888",
      "Connection": "keep-alive",
      "Upgrade-Insecure-Requests": "1",
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 11_2_2) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/88.0.4324.192 Safari/537.36",
      "Accept": "text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9",
      "Sec-Fetch-Site": "same-origin",
      "Sec-Fetch-Mode": "navigate",
      "Sec-Fetch-User": "?1",
      "Sec-Fetch-Dest": "document",
      "Referer": "http://localhost:8888/tree/Documents/Ocaml",
      "Accept-Encoding": "gzip, deflate, br",
      "Accept-Language": "zh-CN,zh;q=0.9",
      "Cookie": "_xsrf=2|2bb76236|74b2991b0a8f42958df6fc979704a9b6|1613634495; username-localhost-8890=\"2|1:0|10:1614692109|23:username-localhost-8890|44:OWU4Mzg2ODg2YzJjNGM2ODlkNTY4MGZjZGJkYjk1Nzc=|698e95ba8193fe4196417b23f0c14e94e983b193ef8ed492807cb188ef6b0ef6\"; username-localhost-8889=\"2|1:0|10:1614700881|23:username-localhost-8889|44:MzUzZmRjZWM1MTE2NGNjMWI2MTZhM2Y0MDI3N2NmN2U=|54ff7c099fa3105baa06bdb896799b1ab3d3b92ed5dc57450572d691c5fab92f\"; username-localhost-8888=\"2|1:0|10:1614704335|23:username-localhost-8888|44:MGI2MmQ4MWFkZjBlNDYyZGE3NTMzNGI1ZTFjZDkyNzU=|1c6a9a958d8e2ae992829edf6479ba8b82b16b8f5ceff411606c9d04f15ddaab\""
    }
[E 13:11:00.714 NotebookApp] 500 GET /notebooks/Documents/Ocaml/%E6%9C%AA%E5%91%BD%E5%90%8D1.ipynb (::1) 187.18ms referer=http://localhost:8888/tree/Documents/Ocaml
`

**Comment by Naereen** [comment]
First of all, I'm sorry for the time losted in the process...
My tiny <https://github.com/Naereen/Jupyter-NBConvert-OCaml/> is far from being stable and solid.

I wrote it in 2017, and never tried to install or use it again since then.
From what you showed, I guess my small project is no longer compatible with the recent version of traitlets:
```python
  File "/Users/mengziweidemac/opt/anaconda3/lib/python3.8/site-packages/jupyter_nbconvert_ocaml/__init__.py", line 99, in template_paths
    return super().template_paths + [os.path.join(os.path.dirname(__file__), "templates")]
[...]
  File "/Users/mengziweidemac/opt/anaconda3/lib/python3.8/site-packages/traitlets/traitlets.py", line 1574, in trait_defaults
    raise TraitError("'%s' is not a trait of '%s' "
traitlets.traitlets.TraitError: 'template_paths' is not a trait of 'OCamlExporter' instances
```
Regardless of the huge trace back showed before, that part is a mistake in my code which uses `super().template_paths`.

I'll check out the last documentation of traitlets, and try to fix this.

**Comment by Naereen** [comment]
Can you try to edit your local version of /Users/mengziweidemac/opt/anaconda3/lib/python3.8/site-packages/jupyter_nbconvert_ocaml/__init__.py on line 99, and do this change:
```diff
-    return super().template_paths + [os.path.join(os.path.dirname(__file__), "templates")]
+    paths = [os.path.join(os.path.dirname(__file__), "templates")]
+    try: paths += super().template_path
+    except: print("No super().template_path")
+    try: paths += super().template_paths
+    except: print("No super().template_paths")
+    return paths
```
(red line means delete this line, green lines mean add them) And then run again what you tried to obtain the 500 error?

I think there might be an inconsistency between versions of nbconvert < 6.0 and >= 6.0, [as the new version changed between `template_path` to `template_paths`](https://nbconvert.readthedocs.io/en/latest/changelog.html?highlight=template_paths#testing-docs-and-builds).

Locally on my version of Python, I've been using nbconvert <6.0 because of dependencies from other packages, so I guess I never tested my Jupyter-NBConvert-OCaml with the newest nbconvert, and if you have a fresh installation I guess you have nbconvert >6.0.
Could you also show me the result of this command (from a terminal, not from python)
```bash
pip show nbconvert traitlets Jupyter-NBConvert-OCaml
```

Thanks!

**Comment by Meng-Ziwei** [comment]
Thanks for your reply. I found a really interesting. As for the newest Jupyter, you can just down the .ipynb file to the .ml file just from File. Maybe it can substitute this package? These I am a little busy and if it is different from what I told you before, I will do these operations later!
Thanks for your enthusiasm for my questions!

**Comment by Naereen** [comment]
Well yes the default exporter works for OCaml and ocaml-jupyter kernel, it uses the `jupyter-nbconvert --script` option, and as such it should remove the comments and don't include the text cells!
Let me know if you obtain a `file.ml` file from your `file.ipynb` notebook, and if it contains the non-code cells as OCaml comments (ie `(* like this *)`).

The only goal of my project was to keep these comment cells!
So if the newest versions can produce `file.ml` that don't remove the comments, my project has become useless :smiley:!
